/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.dt7syntaxcheck.client;

/**
 *
 * @author truon
 */
public class ClientUIFrame extends javax.swing.JFrame {
    private ClientService clientService;

    /**
     * Creates new form ClientUIFrame
     */
    public ClientUIFrame() {
        initComponents();

        // set up callback
        clientService = new ClientService(new MessageListener() {
            @Override
            public void onMessageReceived(String message) {
                pnlErrorLog.setText(pnlErrorLog.getText() + "\n" + message);
            }

            @Override
            public void onDisconnected() {
                pnlErrorLog.setText(pnlErrorLog.getText() + "\nDisconnected from server.");
            }
        });

        // non-blocking task
        clientService.connect("localhost", 5000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblHeader = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlCodeInput = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        btnCheck = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlLog = new javax.swing.JScrollPane();
        pnlErrorLog = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHeader.setText("Code Syntax Checker Client");

        pnlMain.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 54));

        pnlCodeInput.setText("asdsadsadsa sad  sad  das dsa d d asd asd ad ");
        pnlCodeInput.setPreferredSize(new java.awt.Dimension(600, 52));
        jScrollPane1.setViewportView(pnlCodeInput);

        pnlMain.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 500));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] { 0 };
        jPanel2Layout.rowHeights = new int[] { 0, 10, 0 };
        jPanel2.setLayout(jPanel2Layout);

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(btnCheck, gridBagConstraints);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(btnClear, gridBagConstraints);

        pnlMain.add(jPanel2, java.awt.BorderLayout.LINE_END);

        pnlLog.setPreferredSize(new java.awt.Dimension(300, 22));

        pnlErrorLog.setText("asdsadsadsa sad  sad  das dsa d d asd asd ad ");
        pnlLog.setViewportView(pnlErrorLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(lblHeader)
                                                        .addGap(243, 243, 243))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                754, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                754, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblHeader)
                                .addGap(14, 14, 14)
                                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 361,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addGap(12, 12, 12)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCheckActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnClear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JEditorPane pnlCodeInput;
    private javax.swing.JEditorPane pnlErrorLog;
    private javax.swing.JScrollPane pnlLog;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
